adds `hasEmptyString()` function; closes #78
Open-Systems-Pharmacology/OSPSuite.RUtils pull request #84
Opened 2022-03-04 08:54 UTC by IndrajeetPatil

Since the function is designed to check for _any_ empty strings, I think `hasEmptyString()` is a better name, and is similar to `hasOnlyDistinctValues()`.

2022-03-04 10:22 UTC, PavelBal commented
Do you have a use case for this resp. where would you do it now?

2022-03-04 10:23 UTC, IndrajeetPatil commented
For example, output paths, parameter paths, etc. vectors can't be `""`.

2022-03-04 10:24 UTC, IndrajeetPatil commented
I currently do this in `sensitivityCalculation()` function in _esqlabsR_.

2022-03-04 10:25 UTC, PavelBal requested changes

2022-03-04 10:25 UTC, PavelBal commented on tests/testthat/test-error-checks.R
> +  expect_false(hasEmptyString(list(NA, "x", "y")))
If `hasEmptyString(NA)` is `TRUE`, then `hasEmptyString(c(NA, "x", "y"))` should also be `TRUE`, otherwise it does not make sense to me.

2022-03-07 14:47 UTC, msevestre commented
looks good to  me

2022-03-07 14:47 UTC, msevestre approved these changes

2022-03-07 14:57 UTC, PavelBal approved these changes

2022-03-07 15:10 UTC, merged